### ISSUE TITLE
Adicionar HOWTOs às prioridades?

### ISSUE THREAD

**Issue by jonesmartins** [python/python-docs-pt-br#239]
Dado que, das [prioridades de tradução](https://github.com/python/python-docs-pt-br/wiki/Prioridades), tutoriais têm máxima prioridade, acho que HOWTOs têm condição similar aos tutoriais, então sugiro adicionar HOWTOs à prioridade máxima. 

Links para todos os HOWTOs no Transifex:
- [howto--annotations](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--annotations)
- [howto--argparse](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--argparse)
- [howto--argparse-optparse](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--argparse-optparse)
- [howto--clinic](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--clinic)
- [howto--cporting](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--cporting)
- [howto--curses](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--curses)
- [howto--descriptor](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--descriptor)
- [howto--enum](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--enum)
- [howto--free-threading-extensions](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--free-threading-extensions)
- [howto--free-threading-python](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--free-threading-python)
- [howto--functional](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--functional)
- [howto--gdb_helpers](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--gdb_helpers)
- [howto--index](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--index)
- [howto--instrumentation](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--instrumentation)
- [howto--ipaddress](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--ipaddress)
- [howto--isolating-extensions](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--isolating-extensions)
- [howto--logging](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--logging)
- [howto--logging-cookbook](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--logging-cookbook)
- [howto--mro](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--mro)
- [howto--perf_profiling](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--perf_profiling)
- [howto--pyporting](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--pyporting)
- [howto--regex](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--regex)
- [howto--sockets](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--sockets)
- [howto--sorting](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--sorting)
- [howto--timerfd](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--timerfd)
- [howto--unicode](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--unicode)
- [howto--urllib2](https://app.transifex.com/python-doc/python-newest/translate/#pt_BR/howto--urllib2)

**Comment by adorilson** [comment]
O tutorial tem prioridade máxima, primariamente, por definição da PEP 545.

Em algum momento, eu pensei mesmo em priorizar a seção howto, mas acabei não colocando em discussão.
Portanto, concordo que deva ser priorizada, mas não em prioridade máxima. Penso que seria em Prioridade 1, após faq.

**Comment by rffontenelle** [comment]
Adicionado às [Prioridades](https://github.com/python/python-docs-pt-br/wiki/Prioridades)
