### ISSUE TITLE
Atualização das prioridades

### ISSUE THREAD

**Issue by adorilson** [python/python-docs-pt-br#240]
Em complemento a issue #239, sugiro as seguintes mudanças nas prioridades:

1. acrescentar /using em prioridade 1
2. Deixar prioridade 2 com:
 venv
 math
 tkinter
 random
 string
 datetime
 tk
 re
 os
 csv
 turtle

Prioridade 2 foi definida a partir de https://plausible.io/docs.python.org/pages?period=12mo (filtrado por  /pt-br/3/library)

**Comment by rffontenelle** [comment]
Feito: https://github.com/python/python-docs-pt-br/wiki/Prioridades
