### ISSUE TITLE
Variable error in translation of csv.po

### ISSUE THREAD

**Issue by marcorichetta** [python/python-docs-pt-br#36]
Hi!

I'm part of the team translating the Python Docs to Spanish.
I'm currently with the `csv.po` file and I'm using the your translation for guidance.

I spotted an error in this line.
https://github.com/python/python-docs-pt-br/blob/2fc19485ced1eecd8e4f72a25b856a280ecc8a9c/library/csv.po#L517

- `quoting` should be replaced by `doublequote`

Best regards, Marco.

**Comment by rffontenelle** [comment]
Thanks a lot Marco. I just fixed it in Transifex and it will be available here tomorrow.

Feel free to close the issue (I don't have that permission)
