### ISSUE TITLE
Melhorar transparência da mensagem de erro de compilação

### ISSUE THREAD

**Issue by rffontenelle** [python/python-docs-pt-br#37]
## Problema
Atualmente, nosso [workflow do GH Actions](https://github.com/python/python-docs-pt-br/blob/3.9/.github/workflows/pythonpackage.yml) envia uma mensagem para o grupo Telegram de tradução para pt-br do Python docs na ocorrência de erro de sintaxe durante o job `build-warn-as-err `. Esta mensagem no Telegram tem um link para a página da [execução do workflow](https://github.com/python/python-docs-pt-br/actions) que finalizou com erro, onde está o relatório como artefato baixável.

Porém, atualmente o relatório está disponível apenas para quem está autenticado no GitHub. Quem não está autenticado não tem acesso algum para descobrir exatamente qual página falhou.

## Ações
Melhorar a transparência da mensagem de erro de sintaxe, permitindo acessá-las mesmo não estando autenticado.

Opções:
- Analisar recursos do GitHub Actions para exibir os erros na publicamente no próprio output da execução, ou do artefato estar disponível publicamente
- Migrar para Travis (output do Travis está publicamente visível)
- outra?

**Comment by rougeth** [comment]
Talvez criar uma issue no repositório com o output?

**Comment by rffontenelle** [comment]
É uma boa ideia. Descobri hoje um bot do GitHub para Telegram que notifica de novos issues, então poderíamos configurar 1) abertura de issues no caso de falha no workflow e 2) notificação no grupo de telegram quando da abertura do issue
