### ISSUE TITLE
Formatação de __future__ tá muito zoada.

### ISSUE THREAD

**Issue by adorilson** [python/python-docs-pt-br#4]
Módulo  [\_\_future\_\_](https://docs.python.org/pt-br/3.8/library/__future__.html#module-__future__) tá praticamente traduzido, mas a formatação está muito zoada.

Rever no [transifex](https://www.transifex.com/python-doc/python-newest/translate/#pt_BR/library--__future__/).

**Comment by rffontenelle** [comment]
Notei que tradução de máquina (ex. Google Translate) geralmente separa a sintaxe de macros, ao passo que provavelmente temos que conferir toda a documentação por esses erros de formatação. Talvez algum script nos permita navegar por todo código à procura de formatações incorretas seja o melhor caminho, considerando o tamanho da Python Doc.

Exemplos de problema: "algum-texto :mod:" para "algum texto: mod:" (note o espaço adicionado após ":") e até tradução de  "algum-texto :file:" para "algum-texto: arquivo:" (macro file virou "arquivo")

**Comment by rffontenelle** [comment]
Me parece que a documentação do `library/__future__` está boa agora. Dá uma olhada na documentação traduzida que anexei ([`__future__.zip`](https://github.com/python/python-docs-pt-br/files/4044130/__future__.zip)) e veja se esta issue pode ser finalizada.

**Comment by rffontenelle** [comment]
@adorilson Podemos fechar este issue? Como mencionei __future__ me parece bom agora.
