### ISSUE TITLE
Servir a documentação em um site próprio (ex., GitHub Pages)

### ISSUE THREAD

**Issue by rffontenelle** [python/python-docs-pt-br#42]
Servir a documentação em um site da própria equipe (ex., GitHub Pages) poderia nos permitir ver como ficará a documentação em produção, além de, em épocas de sprint, permitir executar em menos espaço de tempo o script de compilação de documentação e tanto encontrar rapidamente erros de tradução quanto permitir melhor visualização.

**Comment by glauesppen** [comment]
Já temos algum template em mente?

**Comment by adorilson** [comment]
Olá, @glauesppen 

Template que você fala é o HTML/CSS?

Se for, isso tá feito. É a o da documentação oficial já. 
Se você fizer o clone desse repositório e executar

```
make venv
source venv/bin/activate
make build
make serve
``` 

Vai conseguir servir a documentação na sua máquina.
O que se quer é colocar isso em um servidor na internet.

Deve dar um erro no build, mas só alterar o arquivo Makefile, mudando a linha 
```
BRANCH              := $(shell git branch --show-current)
```

para 

```
BRANCH              := $(shell git branch)
```

**Comment by glauesppen** [comment]
Oi @adorilson !

Fiquei um pouco confusa entao.. O que @rffontenelle comentou seria para qual finalidade? Queria dar suporte a este repo :)
Obrigada!

**Comment by adorilson** [comment]
Para essas finalidades que ele citou:

>  permitir ver como ficará a documentação em produção, além de, em épocas de sprint, permitir executar em menos espaço de tempo o script de compilação de documentação e tanto encontrar rapidamente erros de tradução quanto permitir melhor visualização.

Contudo, eu não sei se isso ainda é realmente necessário (e se tem uma relação custo/beneficio favorável). Antigamente o processo de atualizaço do docs.python.org era manual. Hoje é automática e feita toda noite.

@rffontenelle Qual a sua opinião sobre isso atualmente?
