### ISSUE TITLE
Migrar para versão 3.10

### ISSUE THREAD

**Issue by rffontenelle** [python/python-docs-pt-br#45]
[O projeto Python será atualizado para 3.10 no dia 6 de junho](https://www.transifex.com/python-doc/python-newest/announcements/12597/). No mesmo dia, é bom migrarmos nosso branch padrão também para 3.10.

## Passos:

1. Criar branch 3.10 a partir do 3.9
2. No Makefile, variável STABLEBRANCH, mudar "3.8" para "3.9"
3. No Makefile, variável OLDSTABLEBRANCHES, adicionar "3.8"
4. No .github/workflows/pythonpackage.yml, variável BRANCH, mudar "3.9" para "3.10"
5. Fazer push das alterações para o GitHub 
6. Mover branch principal para 3.10

## Comandos (não testados):

```bash
git checkout 3.9
git checkout -b 3.10
sed -i Makefile \
    -e '/^STABLEBRANCH/s/3.8/3.9/' \
    -e '/^OLDSTABLEBRANCHES/s/3.7.*/3.8 &/'
sed -i .github/workflows/pythonpackage.yml \
    '/BRANCH:/s/3.9/3.10/'
git add Makefile .github/workflows/pythonpackage.yml
git commit -m 'Update branch to 3.10'
git push --set-upstream origin 3.10
git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/3.10
```

**Comment by adorilson** [comment]
Ideia: criar um script com tudo isso aí que recebe a nova versão como paramentro.

**Comment by rffontenelle** [comment]
Executado
