### ISSUE TITLE
Traduzir library/stdtypes

### ISSUE THREAD

**Issue by adorilson** [python/python-docs-pt-br#7]
Após as seções prioritárias, [library/stdtypes](https://docs.python.org/pt-br/3/library/stdtypes.html) é uma seção importante para ser [traduzida](https://www.transifex.com/python-doc/python-newest/translate/#pt_BR/library--stdtypes/). Pois aprofundamenta conceitos apresentados no tutorial, além de ser uma material de referência bastante consultado. Já está parcialmente traduzida.

**Comment by vinigfer** [comment]
Olá @adorilson . Podes atualizar o link na palavra "traduzida"? O mesmo acaba caindo em uma página 404 - Page not found.
Acredito que também posso fazer a tradução alterando diretamente o arquivo https://github.com/python/python-docs-pt-br/blob/3.7/library/stdtypes.po certo? Mas se a ferramenta transifex é indicada/obrigatória, gostaria de utilizá-la.
Fico no teu aguardo!

**Comment by vinigfer** [comment]
Acho que entendi porque recebi um erro 404. Ainda não tinha me juntado à equipe no transifex.
https://www.transifex.com/python-doc/python-newest/
Estou aguardando aprovação deles (ou outro direcionamento seu) para começar.

Acho que seria interessante atualizarmos o README deste projeto descrevendo melhor como as pessoas podem ajudar na tradução.

**Comment by adorilson** [comment]
Olá, @vinigfer.

Estamos discutindo sobre como melhorar o processo de traduçao.
E o README desse repositorio deverá ser um ponto de melhoria.  

O ponto central de traducao é o grupo no Telegram: https://t.me/pybr_i18n

**Comment by vinigfer** [comment]
@adorilson Consegue encerrar esta issue? A seção já foi traduzida

**Comment by adorilson** [comment]
Ótimo trabalho, @vinigfer. Obrigado.
