### ISSUE TITLE
Typo in functional.po

### ISSUE THREAD

**Issue by JelleZijlstra** [python/python-docs-pt-br#84]
In this line "Programção" should be "Programação" I believe. (Sorry for not reporting in Portuguese!)

https://github.com/python/python-docs-pt-br/blob/02a6ea6d87abec52dd1e6ce398020a653357d081/library/functional.po#L29

Originally reported in python/cpython#105206.

**Comment by rffontenelle** [comment]
Thanks for the heads up. Fixed in Transifex, published docs will be receive the update in a few hours.
